In [125]:
import pandas as pd
import numpy as np
df = pd.read_csv("data/data.csv", sep= ";",encoding="cp1254") 
df.head(5)

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Chief_complain,Mental,Pain,NRS_pain,...,BT,Saturation,KTAS_RN,Diagnosis in ED,Disposition,KTAS_expert,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,71,3,3,2,right ocular pain,1,1,2,...,36.6,100,2,Corneal abrasion,1,4,2,86,"5,00",1
1,1,1,56,12,3,2,right forearm burn,1,1,2,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,"3,95",1
2,2,1,68,8,2,2,"arm pain, Lt",1,1,2,...,36.6,98,4,"Fracture of surgical neck of humerus, closed",2,5,4,862,"1,00",1
3,1,2,71,8,1,1,ascites tapping,1,1,3,...,36.5,NaN,4,Alcoholic liver cirrhosis with ascites,1,5,6,108,"9,83",1
4,1,2,58,4,3,1,"distension, abd",1,1,3,...,36.5,NaN,4,Ascites,1,5,8,109,"6,60",1

In [126]:
df.shape

(1267, 24)

In [127]:
df_clean = df.copy()

    If you use a copy of the original while keeping the original unchanged, then you can refer back to all the untouched data when needed, plus if something goes wrong with copy of the original, another copy can be made from the original which has no changes so its like a fresh start.

In [128]:
df_clean.info()
df_clean.columns

<class 'pandas.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Group                     1267 non-null   int64
 1   Sex                       1267 non-null   int64
 2   Age                       1267 non-null   int64
 3   Patients number per hour  1267 non-null   int64
 4   Arrival mode              1267 non-null   int64
 5   Injury                    1267 non-null   int64
 6   Chief_complain            1267 non-null   str
 7   Mental                    1267 non-null   int64
 8   Pain                      1267 non-null   int64
 9   NRS_pain                  1267 non-null   str
 10  SBP                       1267 non-null   str
 11  DBP                       1267 non-null   str
 12  HR                        1267 non-null   str
 13  RR                        1267 non-null   str
 14  BT                        1267 non-null   str
 15  Saturation                579 non-null    str
 16  KTAS_RN                   1267 non-null   int64
 17  Diagnosis in ED           1265 non-null   str
 18  Disposition               1267 non-null   int64
 19  KTAS_expert               1267 non-null   int64
 20  Error_group               1267 non-null   int64
 21  Length of stay_min        1267 non-null   int64
 22  KTAS duration_min         1267 non-null   str
 23  mistriage                 1267 non-null   int64
dtypes: int64(14), str(10)
memory usage: 237.7 KB

Index(['Group', 'Sex', 'Age', 'Patients number per hour', 'Arrival mode',
       'Injury', 'Chief_complain', 'Mental', 'Pain', 'NRS_pain', 'SBP', 'DBP',
       'HR', 'RR', 'BT', 'Saturation', 'KTAS_RN', 'Diagnosis in ED',
       'Disposition', 'KTAS_expert', 'Error_group', 'Length of stay_min',
       'KTAS duration_min', 'mistriage'],
      dtype='str')

In [129]:
df_clean.dtypes

Group                       int64
Sex                         int64
Age                         int64
Patients number per hour    int64
Arrival mode                int64
Injury                      int64
Chief_complain                str
Mental                      int64
Pain                        int64
NRS_pain                      str
SBP                           str
DBP                           str
HR                            str
RR                            str
BT                            str
Saturation                    str
KTAS_RN                     int64
Diagnosis in ED               str
Disposition                 int64
KTAS_expert                 int64
Error_group                 int64
Length of stay_min          int64
KTAS duration_min             str
mistriage                   int64
dtype: object

    This data set includes 24 columns for 24 differnt variables taken from a patients record. There are also 1267 rows for 1267 patients who's data has been collected. Vitals signs are using str, probally becuase of missing values and column "titles" are also strings

In [130]:
df_clean.loc[[0,1,2,3,4],("Age","Sex","SBP","DBP","HR","Saturation","KTAS_RN","KTAS_expert")]

   Age  Sex  SBP  DBP   HR Saturation  KTAS_RN  KTAS_expert
0   71    2  160  100   84        100        2            4
1   56    1  137   75   60        NaN        4            5
2   68    1  130   80  102         98        4            5
3   71    2  139   94   88        NaN        4            5
4   58    2   91   67   93        NaN        4            5

In [131]:
df_clean.iloc[[0,1,2,3,4],[1,2,10,11,12,15,16,19]]

   Sex  Age  SBP  DBP   HR Saturation  KTAS_RN  KTAS_expert
0    2   71  160  100   84        100        2            4
1    1   56  137   75   60        NaN        4            5
2    1   68  130   80  102         98        4            5
3    2   71  139   94   88        NaN        4            5
4    2   58   91   67   93        NaN        4            5

In [132]:
df_clean = df_clean.rename(columns = {"Saturation":"SpO2","KTAS_RN":"Nurse_KTAS","KTAS_expert":"Expert_KTAS","Chief_complain":"Chief_complaint"})

In [133]:
df_clean.isnull().sum().sort_values(ascending=False)

SpO2                        688
Diagnosis in ED               2
Group                         0
Sex                           0
Arrival mode                  0
Injury                        0
Age                           0
Patients number per hour      0
Mental                        0
Chief_complaint               0
SBP                           0
Pain                          0
DBP                           0
HR                            0
RR                            0
NRS_pain                      0
BT                            0
Nurse_KTAS                    0
Disposition                   0
Expert_KTAS                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

Saturation has the most missing values, with 688 missing values and Diagnosis in ED also has 2 missing values.

In [134]:
pd.set_option('display.max_rows',None)
cols = ["Chief_complaint", "NRS_pain", "SBP","DBP","HR","RR","BT","SpO2"]

for col in cols:
    print(f"\n{col}")
    print(df_clean[col].value_counts())

Chief_complaint
Chief_complaint
abd pain                                 72
dyspnea                                  60
dizziness                                59
fever                                    45
ant. chest pain                          44
Open Wound                               31
headache                                 30
epigastric pain                          22
mental change                            22
general weakness                         21
pain, chest                              16
vomiting                                 16
hematemesis                              14
Left chest pain                          12
Abd. pain                                12
Lt flank pain                            11
syncope                                  10
dysarthria                               10
abdomen pain                             10
palpitation                               9
Vaginal Bleeding                          9
facial injury                             9
RUQ pain                                  8
Urticarial rash                           8
melena                                    8
pain, abdominal                           8
post seizure                              7
hematochezia                              7
H-Headache                                7
pain, low back                            7
Rt. flank pain                            7
epistaxis                                 7
distension, abd                           6
Rt. side motor weakness                   6
ocular pain, Lt.                          6
HA                                        6
Ankle Injury                              6
Discomfort, Chest                         6
anxiety                                   6
ocular pain, Rt.                          6
cough                                     6
diarrhea                                  6
acute epigastric pain                     5
??                                        5
skin rash                                 5
both leg pain                             5
upper abdominal pain                      5
LLQ pain                                  5
RLQ pain                                  5
pain, flank                               5
dysuria                                   5
myalgia                                   5
leg pain                                  5
Convulsion                                5
nausea                                    5
DZ - Dizziness                            5
LBP - Low back pain                       4
throat pain                               4
acute dyspnea                             4
D - Diarrhea                              4
chest palpitation                         4
Facial Palsy                              4
vaginal bleeding                          4
Rt abd pain                               4
diffuse abdominal pain                    4
????                                      4
finger laceration                         4
Finger Injury                             3
injury, finger                            3
Abdominal pain (finding)                  3
lip laceration                            3
Arm Injury                                3
diffuse chest discomfort                  3
Suicidal Attempt                          3
Motor weakness                            3
Amnesia                                   3
post neck pain                            3
head trauma                               3
blurred vision                            3
abdominal pain, Rt                        3
??? ??                                    3
ocular pain                               3
sorethroat                                3
eyebrow laceration                        3
LOC - Loss of consciousness               3
whirling type vertigo                     3
LOC                                       3
Lt. side weakness                         3
voiding difficulty                        3
altered mentality                         3
sexual violence                           3
hemoptysis                                3
post-CPR state                            3
right ocular pain                         2
ascites tapping                           2
With chest discomfort                     2
Lt. hip joint pain                        2
face laceration                           2
pain, arm                                 2
Seizure Like Activity                     2
swelling, facial                          2
Left leg pain                             2
knee pain                                 2
?? ??                                     2
right hemiparesis                         2
watery diarrhea                           2
HA - Headache                             2
leg pain left                             2
hematuria                                 2
right upper abdominal pain                2
Generalized abdominal pain                2
Pain, Hip                                 2
rt flank pain                             2
Blood Pressure, Low                       2
fever & chill                             2
Catheter removal                          2
AVF malfunction                           2
FB in eye                                 2
scalp lac.                                2
Flank pain, Rt.                           2
low abdominal pain                        2
pain, periumbilical                       2
for A/tapping                             2
laceration, chin                          2
chest discomfort left                     2
pain, foot                                2
?? ???                                    2
RLQ abd. pain                             2
Foreign Body Sense                        2
Lt hemiparesis                            2
Rt hemiparesis                            2
???                                       2
backache                                  2
left motor weakness                       2
distended abdomen                         2
otalgia, Lt.                              2
Foot Injury                               2
ankle pain                                2
left leg pain                             2
finger pain                               2
leg swelling, Lt.                         2
Wrist Injury                              2
head injury                               2
injury, ankle                             2
upper back pain                           2
for PEG tube change                       2
sezure like motion                        2
F/C, C/S                                  2
hypoglycemic symptom                      2
abnormal lab.                             2
forehead laceration                       2
eye discomfort                            2
po medication                             2
DI, drug intoxication                     2
eyelid laceration                         2
alcohol smelling state, drunken state     2
anterior chest discomfort                 2
facial palsy left                         2
skin defect                               2
Lt. hemiparesis                           2
right motor weakness                      2
PTBD malfunction                          2
rigth side weakness                       2
loss of consciousness                     2
rotatory vertigo                          2
nasal bleeding                            2
right forearm burn                        1
arm pain, Lt                              1
Eczema, Eyelid                            1
pain, leg                                 1
Gingival swelling                         1
chin pain                                 1
chest wall pain right                     1
hyperventilation                          1
involuntary movt.                         1
Foreign body sensation in neck            1
needle stick injury                       1
right lower quadrant abdominal pain       1
leg pain, Lt.                             1
left wrist swelling                       1
chest pain rt                             1
V - vomiting                              1
both eye pain                             1
tooth pain                                1
Edema, Cheek                              1
Low Back Pain, Undetermined               1
pain, back                                1
both wrist pain                           1
testis pain                               1
Elbow Injury                              1
occipital area headache                   1
weakness                                  1
low Hb                                    1
AVF site bleeding                         1
acute delirium                            1
oliguria                                  1
both leg  motor weakness                  1
Drug Intoxication                         1
limb paresthesia                          1
generalized urticaria                     1
left facial numbness                      1
arm pain, Rt                              1
erection, penile                          1
PPROM                                     1
abdomen discomfort                        1
?? ??? ??                                 1
hand tingling sense                       1
Dislocation of Jaw                        1
Foreign body sensation in throat          1
Rt. Chest pain                            1
chest wall pain left                      1
F/C-fever/chills                          1
Rt side numbness                          1
PTx - Pneumothorax                        1
lower abdominal pain                      1
left knee swelling                        1
Burn, arm                                 1
Gingival bleeding                         1
anal bleeding                             1
swelling, neck                            1
FB in pharynx                             1
Knee Injury                               1
vaginal spotting                          1
right monoparesis                         1
left eyelid laceration                    1
Chest pain NOS (finding)                  1
Midmenstrual pain                         1
Eye Injury                                1
painful skin lesion                       1
Leg pain, NOS                             1
bleeding, knee                            1
Pain, Ankle                               1
pain, neck                                1
rt. side neck pain                        1
arm pain                                  1
finger laceration wound                   1
pain on Knee                              1
Epigastric discomfort(+)                  1
abd. Distension                           1
for medication                            1
left eye pain                             1
VOIDING PAIN                              1
Pain, Eye                                 1
left thigh swelling                       1
??? ? ???                                 1
Lower Back Pain                           1
left forearm pain                         1
both leg cellulitis                       1
RLQ abdominal pain                        1
left side motor weakness                  1
Low abd discomfort                        1
alcohol smell                             1
Voiding Failure                           1
both eyelid swelling                      1
abdominal pain, LUQ                       1
discomfort, chest                         1
right forearm laceration                  1
mandibular pain                           1
Toe injury                                1
otalgia, Rt.                              1
Pain, Hand                                1
Toe redness                               1
ear pain lt                               1
toothache                                 1
Throat Pain                               1
facial painful swelling                   1
toe pain                                  1
left eye swelling                         1
wrist pain, Lt                            1
hypertension                              1
Head Injury                               1
shoulder pain, Lt                         1
right leg injury                          1
abdominal pain, periumbilical area        1
hip pain Lt.                              1
both ocular pain                          1
wrist pain, Rt                            1
Head pain                                 1
leg pain, Rt.                             1
Femur Lesion                              1
Eye Foreign Body                          1
Hand Injury                               1
finger lac.                               1
right shoulder pain                       1
foot swelling                             1
elbow painful swelling                    1
pain, chest wall, Rt                      1
elbow painful swelling lt.                1
right chest pain                          1
Chin swelling                             1
Pain, ?nus                                1
burn, face                                1
TMJ pain                                  1
shoulder pain, both                       1
shoulder pain, Rt                         1
pain, chest wall                          1
lower chest wall pain                     1
pain, tooth                               1
Burn, hand                                1
general ache                              1
visual disturbance                        1
scrotal pain                              1
foreign body ingestion                    1
ocular injury, Lt.                        1
lower extremity paraparesis               1
bee sting                                 1
pelvic pain, Lt                           1
right elbow pain                          1
chest discomfort                          1
Rt. shoulder pain                         1
Hip joint pain                            1
pain, facial                              1
buttock pain                              1
wrist laceration                          1
both shoulder pain                        1
Injury, Leg                               1
COCCYGEAL PAIN                            1
tooth pain, Lt                            1
pain, shoulder                            1
Rt.arm weakness                           1
high BSL                                  1
Nasal swelling                            1
Sudden hearing loss                       1
decreased activity                        1
for ascites tapping                       1
sleeping tendency                         1
rt. side weakness                         1
Retention, Bladder                        1
Free voiding                              1
right hip pain                            1
for L-tube insertion                      1
Voice changes                             1
anemia w/u                                1
light headness                            1
both hand numbness                        1
??? ??? ??                                1
Sexual Abuse of Adult                     1
bleeding, gingival                        1
laceration, scalp                         1
nasal injury                              1
Near syncope                              1
depression                                1
hallucination                             1
erythematous papule                       1
Suicidal thoughts (finding)               1
right nasal bleeding                      1
seizure                                   1
Delusional Idea                           1
cerebral concussion                       1
Confusion state                           1
scratch wound                             1
FB in esophagus                           1
left side weakness                        1
skin eruption                             1
Chemical Burn                             1
Suicidal ideation                         1
CT film copy                              1
Abnormality, Visual Acuity                1
urinary Sx.-symptom                       1
for examination                           1
right side weakness                       1
desaturation                              1
eye trauma                                1
Discomfort, Throat                        1
facial lesion                             1
Fever, Unspecified                        1
itching                                   1
copy                                      1
Dental Problem                            1
mood depression                           1
arrest                                    1
hiccup                                    1
confuse mentality                         1
left diplopia                             1
drowsy mentality                          1
altered mental change                     1
hypoglycemic                              1
Whole body, skin rash                     1
Urinary frequency                         1
C - Coughing                              1
L side weakness                           1
PTBD leaukage                             1
BST high                                  1
numbness                                  1
itching sensation                         1
Aphasia, Motor                            1
confused mental status                    1
diffuse abdominal discomfort              1
Lt. motor weakness                        1
mental confusion                          1
cold                                      1
confusion mentality                       1
Difficulty in voiding                     1
tachycardia                               1
blood tinged sputum                       1
Numbness, Arm                             1
Low abd. pain                             1
perm cath. malfunction                    1
hand laceration                           1
medication                                1
Hyperkalemia (disorder)                   1
Drug Allergy                              1
For  IV injection                         1
right lower abdominal pain                1
eye pain left eye                         1
Pain, Abdomen                             1
oral bleeding                             1
ocular pain, both                         1
decerased visual acuity                   1
Foreign body in throat                    1
swelling                                  1
vaginal discharge                         1
abdomen distension                        1
behavior change                           1
G/W-General weakness                      1
Sensory, Decreased                        1
orthopnea                                 1
Name: count, dtype: int64

NRS_pain
NRS_pain
#BOŞ!    556
3        278
4        141
5        136
6         70
2         38
7         33
8          9
10         3
1          2
9          1
Name: count, dtype: int64

SBP
SBP
120    125
110    117
140     89
100     84
130     79
150     48
160     36
??      25
137     17
136     14
149     14
141     13
180     13
138     13
124     12
119     12
132     12
170     12
90      12
139     11
121     11
143     11
129     11
131     11
163     11
152     10
144     10
156     10
145     10
134     10
135      9
118      9
80       9
165      9
122      9
142      9
115      9
154      9
148      8
116      8
123      8
102      8
190      8
117      8
159      8
146      8
133      7
161      7
166      7
114      7
153      7
164      6
113      6
194      6
158      6
126      6
101      6
157      6
169      5
125      5
162      5
200      5
108      5
105      5
151      5
168      5
128      5
111      5
147      5
107      5
99       5
91       4
196      4
178      4
70       4
197      4
155      4
182      4
167      4
199      3
176      3
210      3
187      3
96       3
109      3
127      3
112      3
179      3
204      3
177      3
171      3
86       3
94       3
181      3
97       3
214      2
50       2
106      2
191      2
198      2
183      2
95       2
202      2
173      2
205      2
103      2
203      2
60       2
220      2
65       1
189      1
93       1
98       1
195      1
174      1
75       1
211      1
193      1
275      1
201      1
104      1
79       1
221      1
233      1
206      1
186      1
213      1

??. Chief complaint, SBP, DBP , HR, RR, BT, SPO2
????. Cheif complaint
??? ?? Cheif complaint
?? ??. Cheif complaint
?? ??? Cheif complaint
??? Chief complaint
?? ??? ?? Chief complaint
??? ? ???  Chief complaint 
??? ??? ?? Chief complaint 
#BOŞ!  NRS_pain 

isnull() detects empty values, not non-numeric values so it would not detect things like ?? and #BO$!

In [135]:
df_clean = df_clean.replace(["??","#BOŞ!","????","??? ??","?? ??","?? ???","??? ? ???","???","?? ??? ??","??? ??? ??"],pd.NA)

In [136]:
df_clean.isnull().sum().sort_values(ascending=False)

SpO2                        697
NRS_pain                    556
DBP                          29
SBP                          25
RR                           22
Chief_complaint              21
HR                           20
BT                           18
Diagnosis in ED               2
Mental                        0
Arrival mode                  0
Injury                        0
Sex                           0
Age                           0
Group                         0
Patients number per hour      0
Pain                          0
Nurse_KTAS                    0
Disposition                   0
Expert_KTAS                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

There has been an increase even in catergories that showed no null early becuase we turned the invaild strings into an object that counts as null.

In [137]:
null=(df_clean.isnull().mean()*100)
print(null[null>0].round(2).sort_values(ascending=False))

SpO2               55.01
NRS_pain           43.88
DBP                 2.29
SBP                 1.97
RR                  1.74
Chief_complaint     1.66
HR                  1.58
BT                  1.42
Diagnosis in ED     0.16
dtype: float64

In [138]:
df_clean[['NRS_pain','SBP','DBP','HR','RR','BT','SpO2','KTAS duration_min']].info(),

<class 'pandas.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NRS_pain           711 non-null    str
 1   SBP                1242 non-null   str
 2   DBP                1238 non-null   str
 3   HR                 1247 non-null   str
 4   RR                 1245 non-null   str
 5   BT                 1249 non-null   str
 6   SpO2               570 non-null    str
 7   KTAS duration_min  1267 non-null   str
dtypes: str(8)
memory usage: 79.3 KB

(None,)

    Because "??", "#BOŞ!" and decimals with commas are strings, the rest of the numbers in that column will also be assigned as string to match those values.

In [139]:
cols = ["NRS_pain","SBP","DBP","HR","RR","BT","SpO2"] 

for col in cols:
    df_clean[col] = pd.to_numeric(df_clean[col],errors="coerce")

df_clean.describe()

,Group,Sex,Age,Patients number per hour,Arrival mode,Injury,Mental,Pain,NRS_pain,SBP,...,HR,RR,BT,SpO2,Nurse_KTAS,Disposition,Expert_KTAS,Error_group,Length of stay_min,mistriage
count,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,711.000000,1242.000000,...,1247.000000,1245.000000,1249.000000,570.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000
mean,1.456985,1.521705,54.423836,7.519337,2.820837,1.192581,1.105762,0.563536,4.104079,133.648953,...,83.963111,19.506827,36.580624,97.024561,3.335438,1.609313,3.265983,0.558011,11016.102605,0.250197
std,0.498343,0.499726,19.725033,3.160563,0.807904,0.394482,0.447768,0.496143,1.419332,27.275639,...,16.644096,2.016649,0.545708,4.350556,0.885391,1.157983,0.885803,1.571489,80446.092065,0.628250
min,1.000000,1.000000,16.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,50.000000,...,32.000000,14.000000,35.000000,20.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,37.000000,5.000000,2.000000,1.000000,1.000000,0.000000,3.000000,114.000000,...,72.000000,18.000000,36.200000,97.000000,3.000000,1.000000,3.000000,0.000000,133.000000,0.000000
50%,1.000000,2.000000,57.000000,7.000000,3.000000,1.000000,1.000000,1.000000,4.000000,130.000000,...,82.000000,20.000000,36.500000,98.000000,3.000000,1.000000,3.000000,0.000000,274.000000,0.000000
75%,2.000000,2.000000,71.000000,10.000000,3.000000,1.000000,1.000000,1.000000,5.000000,150.000000,...,96.000000,20.000000,36.800000,98.000000,4.000000,2.000000,4.000000,0.000000,606.500000,0.000000
max,2.000000,2.000000,96.000000,17.000000,7.000000,2.000000,4.000000,1.000000,10.000000,275.000000,...,148.000000,30.000000,41.000000,100.000000,5.000000,7.000000,5.000000,9.000000,709510.000000,2.000000

In [140]:
df_clean.isnull().sum().sort_values(ascending=False)

SpO2                        697
NRS_pain                    556
DBP                          29
SBP                          25
RR                           22
Chief_complaint              21
HR                           20
BT                           18
Diagnosis in ED               2
Mental                        0
Arrival mode                  0
Injury                        0
Sex                           0
Age                           0
Group                         0
Patients number per hour      0
Pain                          0
Nurse_KTAS                    0
Disposition                   0
Expert_KTAS                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

In [141]:
df_clean.dtypes

Group                         int64
Sex                           int64
Age                           int64
Patients number per hour      int64
Arrival mode                  int64
Injury                        int64
Chief_complaint                 str
Mental                        int64
Pain                          int64
NRS_pain                    float64
SBP                         float64
DBP                         float64
HR                          float64
RR                          float64
BT                          float64
SpO2                        float64
Nurse_KTAS                    int64
Diagnosis in ED                 str
Disposition                   int64
Expert_KTAS                   int64
Error_group                   int64
Length of stay_min            int64
KTAS duration_min               str
mistriage                     int64
dtype: object

In [142]:
df_clean["KTAS duration_min"] = df_clean["KTAS duration_min"].astype(str).str.replace(",", ".", regex=False)
df_clean["KTAS duration_min"] = pd.to_numeric(df_clean["KTAS duration_min"],errors="coerce")
float(df_clean["KTAS duration_min"].max())

17.37

In [143]:
float(df_clean["KTAS duration_min"].min())

1.0

In [144]:
float((df_clean["KTAS duration_min"].mean()).round(3))

5.497

In [145]:
float(df_clean["KTAS duration_min"].median())

4.28

In [146]:
df_clean.shape

(1267, 24)

In [147]:
df_clean.dtypes

Group                         int64
Sex                           int64
Age                           int64
Patients number per hour      int64
Arrival mode                  int64
Injury                        int64
Chief_complaint                 str
Mental                        int64
Pain                          int64
NRS_pain                    float64
SBP                         float64
DBP                         float64
HR                          float64
RR                          float64
BT                          float64
SpO2                        float64
Nurse_KTAS                    int64
Diagnosis in ED                 str
Disposition                   int64
Expert_KTAS                   int64
Error_group                   int64
Length of stay_min            int64
KTAS duration_min           float64
mistriage                     int64
dtype: object

In [148]:
df_clean.isnull().sum()

Group                         0
Sex                           0
Age                           0
Patients number per hour      0
Arrival mode                  0
Injury                        0
Chief_complaint              21
Mental                        0
Pain                          0
NRS_pain                    556
SBP                          25
DBP                          29
HR                           20
RR                           22
BT                           18
SpO2                        697
Nurse_KTAS                    0
Diagnosis in ED               2
Disposition                   0
Expert_KTAS                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

In [149]:
df_clean.columns

Index(['Group', 'Sex', 'Age', 'Patients number per hour', 'Arrival mode',
       'Injury', 'Chief_complaint', 'Mental', 'Pain', 'NRS_pain', 'SBP', 'DBP',
       'HR', 'RR', 'BT', 'SpO2', 'Nurse_KTAS', 'Diagnosis in ED',
       'Disposition', 'Expert_KTAS', 'Error_group', 'Length of stay_min',
       'KTAS duration_min', 'mistriage'],
      dtype='str')

In [150]:
df.columns

Index(['Group', 'Sex', 'Age', 'Patients number per hour', 'Arrival mode',
       'Injury', 'Chief_complain', 'Mental', 'Pain', 'NRS_pain', 'SBP', 'DBP',
       'HR', 'RR', 'BT', 'Saturation', 'KTAS_RN', 'Diagnosis in ED',
       'Disposition', 'KTAS_expert', 'Error_group', 'Length of stay_min',
       'KTAS duration_min', 'mistriage'],
      dtype='str')

In [151]:
df.shape

(1267, 24)

In [152]:
df.dtypes

Group                       int64
Sex                         int64
Age                         int64
Patients number per hour    int64
Arrival mode                int64
Injury                      int64
Chief_complain                str
Mental                      int64
Pain                        int64
NRS_pain                      str
SBP                           str
DBP                           str
HR                            str
RR                            str
BT                            str
Saturation                    str
KTAS_RN                     int64
Diagnosis in ED               str
Disposition                 int64
KTAS_expert                 int64
Error_group                 int64
Length of stay_min          int64
KTAS duration_min             str
mistriage                   int64
dtype: object

In [153]:
df.isnull().sum()

Group                         0
Sex                           0
Age                           0
Patients number per hour      0
Arrival mode                  0
Injury                        0
Chief_complain                0
Mental                        0
Pain                          0
NRS_pain                      0
SBP                           0
DBP                           0
HR                            0
RR                            0
BT                            0
Saturation                  688
KTAS_RN                       0
Diagnosis in ED               2
Disposition                   0
KTAS_expert                   0
Error_group                   0
Length of stay_min            0
KTAS duration_min             0
mistriage                     0
dtype: int64

1. How many rows and columns are in the dataset?
    1.There are 1267 rows and 24 columns, 1267 for 1267 patient records and 24 variables
2. Which column has the most standard missing values?
    2.Saturation, also known as SpO2 in df_clean with 688 missing values, and 697 after turning invalid input into null.
3. Which special values represent missing data?
    3.NaN.
4. Why did some numeric columns initially have the `object` data type?
    4.Some of those values were actually strings making the rest of the column of string type
5. How were the vital-sign columns converted into numeric columns?
    5.Using  pd.to_numeric(df_clean[col],errors="coerce") which would turn the values from string type to float type.
6. How was `KTAS duration_min` converted into numeric data?
    6.Since some of the numbers used a comma instead of a period for decimals, I first replaced the commas with a period to ensure that they would register as a number when converted and not a NaN. Then use pd.to_numeric(df_clean["KTAS duration min"]).
7. Which column was the most difficult to clean?
    7.The Chief complaint column becuase it contained differnt combiantion of ??
8. Why is it useful to preserve the original DataFrame?
    8.If you use a copy of the original while keeping the original unchanged, then you can refer back to all the untouched data when needed, plus if something goes wrong with copy of the original, another copy can be made from the original which has no changes so its like a fresh start.

In [154]:
bins = [0,19,39,59,79,np.inf]
ages = ['AGE_19','AGE_39','AGE_59','AGE_79','AGE_80+']
Ages = pd.cut(df_clean['Age'],bins=bins, labels= ages, include_lowest=True)

df_clean = df_clean.drop(columns=ages, errors='ignore')
age_dummies = pd.get_dummies(Ages, dtype=int)
loc = df_clean.columns.get_loc('Age') + 1

for i, col in enumerate(age_dummies.columns):
    df_clean.insert(loc + i, col, age_dummies[col])
df_clean.head(4)

,Group,Sex,Age,AGE_19,AGE_39,AGE_59,AGE_79,AGE_80+,Patients number per hour,Arrival mode,...,BT,SpO2,Nurse_KTAS,Diagnosis in ED,Disposition,Expert_KTAS,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,71,0,0,0,1,0,3,3,...,36.6,100.0,2,Corneal abrasion,1,4,2,86,5.00,1
1,1,1,56,0,0,1,0,0,12,3,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,3.95,1
2,2,1,68,0,0,0,1,0,8,2,...,36.6,98.0,4,"Fracture of surgical neck of humerus, closed",2,5,4,862,1.00,1
3,1,2,71,0,0,0,1,0,8,1,...,36.5,NaN,4,Alcoholic liver cirrhosis with ascites,1,5,6,108,9.83,1

In [155]:
age_group = pd.cut(df_clean['Age'], bins= bins, include_lowest=True).value_counts().sort_index()
print(age_group)

Age
(-0.001, 19.0]     34
(19.0, 39.0]      309
(39.0, 59.0]      371
(59.0, 79.0]      437
(79.0, inf]       116
Name: count, dtype: int64

In [156]:
print(df_clean['Sex'].unique())
sex_map = {
    1: 'SEX_Female',
    2: 'SEX_Male'
    
}
sex = df_clean['Sex'].map(sex_map)
sex_dummies = pd.get_dummies(sex, dtype=int)
loc = df_clean.columns.get_loc('Sex') + 1

for i, col in enumerate(sex_dummies.columns):
    df_clean.insert(loc + i, col, sex_dummies[col])

df_clean.head(4)

[2 1]

,Group,Sex,SEX_Female,SEX_Male,Age,AGE_19,AGE_39,AGE_59,AGE_79,AGE_80+,...,BT,SpO2,Nurse_KTAS,Diagnosis in ED,Disposition,Expert_KTAS,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,0,1,71,0,0,0,1,0,...,36.6,100.0,2,Corneal abrasion,1,4,2,86,5.00,1
1,1,1,1,0,56,0,0,1,0,0,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,3.95,1
2,2,1,1,0,68,0,0,0,1,0,...,36.6,98.0,4,"Fracture of surgical neck of humerus, closed",2,5,4,862,1.00,1
3,1,2,0,1,71,0,0,0,1,0,...,36.5,NaN,4,Alcoholic liver cirrhosis with ascites,1,5,6,108,9.83,1

In [157]:
df_clean['SEX_Female'].isnull().value_counts(dropna=False)

SEX_Female
False    1267
Name: count, dtype: int64

In [158]:
df_clean['SEX_Male'].isnull().value_counts(dropna=False)

SEX_Male
False    1267
Name: count, dtype: int64

In [159]:
df_clean.tail(4)

,Group,Sex,SEX_Female,SEX_Male,Age,AGE_19,AGE_39,AGE_59,AGE_79,AGE_80+,...,BT,SpO2,Nurse_KTAS,Diagnosis in ED,Disposition,Expert_KTAS,Error_group,Length of stay_min,KTAS duration_min,mistriage
1263,2,2,0,1,81,0,0,0,0,1,...,36.4,97.0,4,Dysuria,1,4,0,1000,2.0,0
1264,2,2,0,1,81,0,0,0,0,1,...,36.2,99.0,3,Dizziness and giddiness,1,3,0,310,4.0,0
1265,2,1,1,0,81,0,0,0,0,1,...,36.6,98.0,3,"Cord compression, unspecified",7,3,0,475,5.0,0
1266,2,2,0,1,87,0,0,0,0,1,...,36.2,98.0,3,Dyspnoea,2,3,0,887,2.0,0

In [160]:
senior = np.where(df_clean['Age'] >= 65,'Yes','No')
loc = df_clean.columns.get_loc('Age') + 1
df_clean.insert(loc, 'Senior',senior)
df_clean.head(2)

,Group,Sex,SEX_Female,SEX_Male,Age,Senior,AGE_19,AGE_39,AGE_59,AGE_79,...,BT,SpO2,Nurse_KTAS,Diagnosis in ED,Disposition,Expert_KTAS,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,0,1,71,Yes,0,0,0,1,...,36.6,100.0,2,Corneal abrasion,1,4,2,86,5.00,1
1,1,1,1,0,56,No,0,0,1,0,...,36.5,NaN,4,"Burn of hand, firts degree dorsum",1,5,4,64,3.95,1

In [161]:
(df_clean['Age'] >= 65).map({True: 'Senior', False: 'Non-Senior'}).value_counts().sort_index()

Age
Non-Senior    800
Senior        467
Name: count, dtype: int64

In [162]:
ture = df_clean['SpO2'].notna()
low_Spo2 = df_clean['SpO2'].lt(95).where(ture).astype("boolean")
loc = df_clean.columns.get_loc('SpO2') + 1
df_clean.insert(loc, 'Low_SpO2',low_Spo2)

In [163]:
low_Spo2 = df_clean['SpO2'].lt(95).where(ture,'Missing').value_counts()
print(low_Spo2)

SpO2
Missing    697
False      523
True        47
Name: count, dtype: int64

Explain why missing SpO₂ values must be kept separate from False.

They are missing, so we dont know what the true value is. Since they could be true or flase, making them false instead of excluding them could make the false to true rate significantly higher than it actually is.

In [184]:
#df_clean[df_clean['mistriage'] == 0] #correct
#df_clean[df_clean['mistriage'] == 1] #over-triage
#df_clean[df_clean['mistriage'] == 2] #under-triage

In [165]:
KTAS_bool = df_clean['KTAS_match'] = df_clean['Expert_KTAS'] == df_clean['Nurse_KTAS']
ktas_match = df_clean.pop("KTAS_match")
loc = df_clean.columns.get_loc('Expert_KTAS') + 1
df_clean.insert(loc,"KTAS_match",ktas_match)
df_clean.head(5)

,Group,Sex,SEX_Female,SEX_Male,Age,Senior,AGE_19,AGE_39,AGE_59,AGE_79,...,Low_SpO2,Nurse_KTAS,Diagnosis in ED,Disposition,Expert_KTAS,KTAS_match,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,0,1,71,Yes,0,0,0,1,...,False,2,Corneal abrasion,1,4,False,2,86,5.00,1
1,1,1,1,0,56,No,0,0,1,0,...,<NA>,4,"Burn of hand, firts degree dorsum",1,5,False,4,64,3.95,1
2,2,1,1,0,68,Yes,0,0,0,1,...,False,4,"Fracture of surgical neck of humerus, closed",2,5,False,4,862,1.00,1
3,1,2,0,1,71,Yes,0,0,0,1,...,<NA>,4,Alcoholic liver cirrhosis with ascites,1,5,False,6,108,9.83,1
4,1,2,0,1,58,No,0,0,1,0,...,<NA>,4,Ascites,1,5,False,8,109,6.60,1

In [166]:
print("Matching:", KTAS_bool.sum())
print("Non-matching:", 1267-KTAS_bool.sum())

Matching: 1081
Non-matching: 186

In [167]:
pd.crosstab(df_clean['mistriage'],df_clean['KTAS_match'])

KTAS_match  False  True
mistriage
0               0   1081
1              55      0
2             131      0

1.In mistriage there is 1 for overtriage, 2 for under and 0 for a correct score.
2.It contains both under, over, and correct match info
3.It does so yea
4.If someone wants to make new catergories, they can be sure to include, under and over, triage, not just mistriage

In [168]:
df_clean2 = df_clean.copy()

In [169]:
df_clean2.duplicated()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37      False
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False
51      False
52      False
53      False
54      False
55      False
56      False
57      False
58      False
59      False
60      False
61      False
62      False
63      False
64      False
65      False
66      False
67      False
68      False
69      False
70      False
71      False
72      False
73      False
74      False
75      False
76      False
77      False
78      False
79      False
80      False
81      False
82      False
83      False
84      False
85      False
86      False
87      False
88      False
89      False
90      False
91      False
92      False
93      False
94      False
95      False
96      False
97      False
98      False
99      False
100     False
101     False
102     False
103     False
104     False
105     False
106     False
107     False
108     False
109     False
110     False
111     False
112     False
113     False
114     False
115     False
116     False
117     False
118     False
119     False
120     False
121     False
122     False
123     False
124     False
125     False
126     False
127     False
128     False
129     False
130     False
131     False
132     False
133     False
134     False
135     False
136     False
137     False
138     False
139     False
140     False
141     False
142     False
143     False
144     False
145     False
146     False
147     False
148     False
149     False
150     False
151     False
152     False
153     False
154     False
155     False
156     False
157     False
158     False
159     False
160     False
161     False
162     False
163     False
164     False
165     False
166     False
167     False
168     False
169     False
170     False
171     False
172     False
173     False
174     False
175     False
176     False
177     False
178     False
179     False
180     False
181     False
182     False
183     False
184     False
185     False
186     False
187     False
188     False
189     False
190     False
191     False
192     False
193     False
194     False
195     False
196     False
197     False
198     False
199     False
200     False
201     False
202     False
203     False
204     False
205     False
206     False
207     False
208     False
209     False
210     False
211     False
212     False
213     False
214     False
215     False
216     False
217     False
218     False
219     False
220     False
221     False
222     False
223     False
224     False
225     False
226     False
227     False
228     False
229     False
230     False
231     False
232     False
233     False
234     False
235     False
236     False
237     False
238     False
239     False
240     False
241     False
242     False
243     False
244     False
245     False
246     False
247     False
248     False
249     False
250     False
251     False
252     False
253     False
254     False
255     False
256     False
257     False
258     False
259     False
260     False
261     False
262     False
263     False
264     False
265     False
266     False
267     False
268     False
269     False
270     False
271     False
272     False
273     False
274     False
275     False
276     False
277     False
278     False
279     False
280     False
281     False
282     False
283     False
284     False
285     False
286     False
287     False
288     False
289     False
290     False
291     False
292     False
293     False
294     False
295     False
296     False
297     False
298     False
299     False
300     False
301     False
302     False
303     False
304     False
305     False
306     False
307     False
308     False
309     False
310     False
311     False
312     False
313     False
314     False
315     False
316     False
317     False
318     False
319     False
320     False
321     False
322     False
323     False
324     False
325     False
326     False
327     False
328     False
329     False
330     False
331     False
332     False
333     False
334     False
335     False
336     False
337     False
338     False
339     False
340     False
341     False
342     False
343     False
344     False
345     False
346     False
347     False
348     False
349     False
350     False
351     False
352     False
353     False
354     False
355     False
356     False
357     False
358     False
359     False
360     False
361     False
362     False
363     False
364     False
365     False
366     False
367     False
368     False
369     False
370     False
371     False
372     False
373     False
374     False
375     False
376     False
377     False
378     False
379     False
380     False
381     False
382     False
383     False
384     False
385     False
386     False
387     False
388     False
389     False
390     False
391     False
392     False
393     False
394     False
395     False
396     False
397     False
398     False
399     False
400     False
401     False
402     False
403     False
404     False
405     False
406     False
407     False
408     False
409     False
410     False
411     False
412     False
413     False
414     False
415     False
416     False
417     False
418     False
419     False
420     False
421     False
422     False
423     False
424     False
425     False
426     False
427     False
428     False
429     False
430     False
431     False
432     False
433     False
434     False
435     False
436     False
437     False
438     False
439     False
440     False
441     False
442     False
443     False
444     False
445     False
446     False
447     False
448     False
449     False
450     False
451     False
452     False
453     False
454     False
455     False
456     False
457     False
458     False
459     False
460     False
461     False
462     False
463     False
464     False
465     False
466     False
467     False
468     False
469     False
470     False
471     False
472     False
473     False
474     False
475     False
476     False
477     False
478     False
479     False
480     False
481     False
482     False
483     False
484     False
485     False
486     False
487     False
488     False
489     False
490     False
491     False
492     False
493     False
494     False
495     False
496     False
497     False
498     False
499     False
500     False
501     False
502     False
503     False
504     False
505     False
506     False
507     False
508     False
509     False
510     False
511     False
512     False
513     False
514     False
515     False
516     False
517     False
518     False
519     False
520     False
521     False
522     False
523     False
524     False
525     False
526     False
527     False
528     False
529     False
530     False
531     False
532     False
533     False
534     False
535     False
536     False
537     False
538     False
539     False
540     False
541     False
542     False
543     False
544     False
545     False
546     False
547     False
548     False
549     False
550     False
551     False
552     False
553     False
554     False
555     False
556     False
557     False
558     False
559     False
560     False
561     False
562     False
563     False
564     False
565     False
566     False
567     False
568     False
569     False
570     False
571     False
572     False
573     False
574     False
575     False
576     False
577     False
578     False
579     False
580     False
581     False
582     False
583     False
584     False
585     False
586     False
587     False
588     False
589     False
590     False
591     False
592     False
593     False
594     False
595     False
596     False
597     False
598     False
599     False
600     False
601     False
602     False
603     False
604     False
605     False
606     False
607     False
608     False
609     False
610     False
611     False
612     False
613     False
614     False
615     False
616     False
617     False
618     False
619     False
620     False
621     False
622     False
623     False
624     False
625     False
626     False
627     False
628     False
629     False
630     False
631     False
632     False
633     False
634     False
635     False
636     False
637     False
638     False
639     False
640     False
641     False
642     False
643     False
644     False
645     False
646     False
647     False
648     False
649     False
650     False
651     False
652     False
653     False
654     False
655     False
656     False
657     False
658     False
659     False
660     False
661     False
662     False
663     False
664     False
665     False
666     False
667     False
668     False
669     False
670     False
671     False
672     False
673     False
674     False
675     False
676     False
677     False
678     False
679     False
680     False
681     False
682     False
683     False
684     False
685     False
686     False
687     False
688     False
689     False
690     False
691     False
692     False
693     False
694     False
695     False
696     False
697     False
698     False
699     False
700     False
701     False
702     False
703     False
704     False
705     False
706     False
707     False
708     False
709     False
710     False
711     False
712     False
713     False
714     False
715     False
716     False
717     False
718     False
719     False
720     False
721     False
722     False
723     False
724     False
725     False
726     False
727     False
728     False
729     False
730     False
731     False
732     False
733     False
734     False
735     False
736     False
737     False
738     False
739     False
740     False
741     False
742     False
743     False
744     False
745     False
746     False
747     False
748     False
749     False
750     False
751     False
752     False
753     False
754     False
755     False
756     False
757     False
758     False
759     False
760     False
761     False
762     False
763     False
764     False
765     False
766     False
767     False
768     False
769     False
770     False
771     False
772     False
773     False
774     False
775     False
776     False
777     False
778     False
779     False
780     False
781     False
782     False
783     False
784     False
785     False
786     False
787     False
788     False
789     False
790     False
791     False
792     False
793     False
794     False
795     False
796     False
797     False
798     False
799     False
800     False
801     False
802     False
803     False
804     False
805     False
806     False
807     False
808     False
809     False
810     False
811     False
812     False
813     False
814     False
815     False
816     False
817     False
818     False
819     False
820     False
821     False
822     False
823     False
824     False
825     False
826     False
827     False
828     False
829     False
830     False
831     False
832     False
833     False
834     False
835     False
836     False
837     False
838     False
839     False
840     False
841     False
842     False
843     False
844     False
845     False
846     False
847     False
848     False
849     False
850     False
851     False
852     False
853     False
854     False
855     False
856     False
857     False
858     False
859     False
860     False
861     False
862     False
863     False
864     False
865     False
866     False
867     False
868     False
869     False
870     False
871     False
872     False
873     False
874     False
875     False
876     False
877     False
878     False
879     False
880     False
881     False
882     False
883     False
884     False
885     False
886     False
887     False
888     False
889     False
890     False
891     False
892     False
893     False
894     False
895     False
896     False
897     False
898     False
899     False
900     False
901     False
902     False
903     False
904     False
905     False
906     False
907     False
908     False
909     False
910     False
911     False
912     False
913     False
914     False
915     False
916     False
917     False
918     False
919     False
920     False
921     False
922     False
923     False
924     False
925     False
926     False
927     False
928     False
929     False
930     False
931     False
932     False
933     False
934     False
935     False
936     False
937     False
938     False
939     False
940     False
941     False
942     False
943     False
944     False
945     False
946     False
947     False
948     False
949     False
950     False
951     False
952     False
953     False
954     False
955     False
956     False
957     False
958     False
959     False
960     False
961     False
962     False
963     False
964     False
965     False
966     False
967     False
968     False
969     False
970     False
971     False
972     False
973     False
974     False
975     False
976     False
977     False
978     False
979     False
980     False
981     False
982     False
983     False
984     False
985     False
986     False
987     False
988     False
989     False
990     False
991     False
992     False
993     False
994     False
995     False
996     False
997     False
998     False
999     False
1000    False
1001    False
1002    False
1003    False
1004    False
1005    False
1006    False
1007    False
1008    False
1009    False
1010    False
1011    False
1012    False
1013    False
1014    False
1015    False
1016    False
1017    False
1018    False
1019    False
1020    False
1021    False
1022    False
1023    False
1024    False
1025    False
1026    False
1027    False
1028    False
1029    False
1030    False
1031    False
1032    False
1033    False
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047    False
1048    False
1049    False
1050    False
1051    False
1052    False
1053    False
1054    False
1055    False
1056    False
1057    False
1058    False
1059    False
1060    False
1061    False
1062    False
1063    False
1064    False
1065    False
1066    False
1067    False
1068    False
1069    False
1070    False
1071    False
1072    False
1073    False
1074    False
1075    False
1076    False
1077    False
1078    False
1079    False
1080    False
1081    False
1082    False
1083    False
1084    False
1085    False
1086    False
1087    False
1088    False
1089    False
1090    False
1091    False
1092    False
1093    False
1094    False
1095    False
1096    False
1097    False
1098    False
1099    False
1100    False
1101    False
1102    False
1103    False
1104    False
1105    False
1106    False
1107    False
1108    False
1109    False
1110    False
1111    False
1112    False
1113    False
1114    False
1115    False
1116    False
1117    False
1118    False
1119    False
1120    False
1121    False
1122    False
1123    False
1124    False
1125    False
1126    False
1127    False
1128    False
1129    False
1130    False
1131    False
1132    False
1133    False
1134    False
1135    False
1136    False
1137    False
1138    False
1139    False
1140    False
1141    False
1142    False
1143    False
1144    False
1145    False
1146    False
1147    False
1148    False
1149    False
1150    False
1151    False
1152    False
1153    False
1154    False
1155    False
1156    False
1157    False
1158    False
1159    False
1160    False
1161    False
1162    False
1163    False
1164    False
1165    False
1166    False
1167    False
1168    False
1169    False
1170    False
1171    False
1172    False
1173    False
1174    False
1175    False
1176    False
1177    False
1178    False
1179    False
1180    False
1181    False
1182    False
1183    False
1184    False
1185    False
1186    False
1187    False
1188    False
1189    False
1190    False
1191    False
1192    False
1193    False
1194    False
1195    False
1196    False
1197    False
1198    False
1199    False
1200    False
1201    False
1202    False
1203    False
1204    False
1205    False
1206    False
1207    False
1208    False
1209    False
1210    False
1211    False
1212    False
1213    False
1214    False
1215    False
1216    False
1217    False
1218    False
1219    False
1220    False
1221    False
1222    False
1223    False
1224    False
1225    False
1226    False
1227    False
1228    False
1229    False
1230    False
1231    False
1232    False
1233    False
1234    False
1235    False
1236    False
1237    False
1238    False
1239    False
1240    False
1241    False
1242    False
1243    False
1244    False
1245    False
1246    False
1247    False
1248    False
1249    False
1250    False
1251    False
1252    False
1253    False
1254    False
1255    False
1256    False
1257    False
1258    False
1259    False
1260    False
1261    False
1262    False
1263    False
1264    False
1265    False
1266    False
dtype: bool

In [170]:
df_clean2.sum()

Group                                                                    1846
Sex                                                                      1928
SEX_Female                                                                606
SEX_Male                                                                  661
Age                                                                     68955
Senior                      YesNoYesYesNoNoNoYesNoNoNoNoNoNoNoYesYesNoNoNo...
AGE_19                                                                     34
AGE_39                                                                    309
AGE_59                                                                    371
AGE_79                                                                    437
AGE_80+                                                                   116
Patients number per hour                                                 9527
Arrival mode                                                             3574
Injury                                                                   1511
Chief_complaint             right ocular painright forearm burnarm pain, L...
Mental                                                                   1401
Pain                                                                      714
NRS_pain                                                               2918.0
SBP                                                                  165992.0
DBP                                                                   98768.0
HR                                                                   104702.0
RR                                                                    24286.0
BT                                                                    45689.2
SpO2                                                                  55304.0
Low_SpO2                                                                   47
Nurse_KTAS                                                               4226
Diagnosis in ED             Corneal abrasionBurn of hand, firts degree dor...
Disposition                                                              2039
Expert_KTAS                                                              4138
KTAS_match                                                               1081
Error_group                                                               707
Length of stay_min                                                   13957402
KTAS duration_min                                                     6965.29
mistriage                                                                 317
dtype: object

In [171]:
df_clean2.drop_duplicates()
df_clean2.head()

,Group,Sex,SEX_Female,SEX_Male,Age,Senior,AGE_19,AGE_39,AGE_59,AGE_79,...,Low_SpO2,Nurse_KTAS,Diagnosis in ED,Disposition,Expert_KTAS,KTAS_match,Error_group,Length of stay_min,KTAS duration_min,mistriage
0,2,2,0,1,71,Yes,0,0,0,1,...,False,2,Corneal abrasion,1,4,False,2,86,5.00,1
1,1,1,1,0,56,No,0,0,1,0,...,<NA>,4,"Burn of hand, firts degree dorsum",1,5,False,4,64,3.95,1
2,2,1,1,0,68,Yes,0,0,0,1,...,False,4,"Fracture of surgical neck of humerus, closed",2,5,False,4,862,1.00,1
3,1,2,0,1,71,Yes,0,0,0,1,...,<NA>,4,Alcoholic liver cirrhosis with ascites,1,5,False,6,108,9.83,1
4,1,2,0,1,58,No,0,0,1,0,...,<NA>,4,Ascites,1,5,False,8,109,6.60,1

In [172]:
df_clean2.shape

(1267, 34)

Just in case it is another patient that was very similar or it was there for a reason, i.e. an example case
There were no duplicates, but its importnat to check anyway just in case before using the data set and giving it to other scientists or like ai or smth.

In [173]:
df_clean.loc[(df_clean["Senior"] == "Yes") & (df_clean["Low_SpO2"]) & (df_clean["HR"] >= 100),["Age","SEX_Female","SEX_Male","DBP","HR","SpO2","Nurse_KTAS","Expert_KTAS"]]

      Age  SEX_Female  SEX_Male    DBP     HR  SpO2  Nurse_KTAS  Expert_KTAS
132    82           0         1  100.0  116.0  68.0           2            1
134    92           1         0   90.0  110.0  88.0           3            2
153    65           0         1    NaN  100.0  94.0           2            1
405    72           1         0   60.0  106.0  93.0           2            2
412    74           1         0   60.0  110.0  91.0           3            3
434    80           0         1   80.0  118.0  76.0           2            2
550    81           1         0   60.0  110.0  93.0           3            3
1093   70           0         1   80.0  100.0  90.0           3            3
1147   77           0         1   80.0  106.0  93.0           3            3
1169   80           1         0   70.0  110.0  93.0           3            3
1182   81           1         0   60.0  100.0  94.0           3            3

In [174]:
mask = (df_clean["Senior"] == "Yes") & (df_clean["Low_SpO2"]) & (df_clean["HR"] >= 100)
mask.sum()

np.int64(11)

In [175]:
df_clean.query('Senior == "Yes" and Low_SpO2 and HR >= 100')[["Age", "SEX_Female","SEX_Male","DBP","HR","SpO2","Nurse_KTAS","Expert_KTAS"]]

      Age  SEX_Female  SEX_Male    DBP     HR  SpO2  Nurse_KTAS  Expert_KTAS
132    82           0         1  100.0  116.0  68.0           2            1
134    92           1         0   90.0  110.0  88.0           3            2
153    65           0         1    NaN  100.0  94.0           2            1
405    72           1         0   60.0  106.0  93.0           2            2
412    74           1         0   60.0  110.0  91.0           3            3
434    80           0         1   80.0  118.0  76.0           2            2
550    81           1         0   60.0  110.0  93.0           3            3
1093   70           0         1   80.0  100.0  90.0           3            3
1147   77           0         1   80.0  106.0  93.0           3            3
1169   80           1         0   70.0  110.0  93.0           3            3
1182   81           1         0   60.0  100.0  94.0           3            3

In [176]:
print(df_clean.query('Senior == "Yes" and Low_SpO2 and HR >= 100')[["Age", "SEX_Female","SEX_Male","DBP","HR","SpO2","Nurse_KTAS","Expert_KTAS"]].reset_index().equals(df_clean.loc[(df_clean["Senior"] == "Yes") & (df_clean["Low_SpO2"]) & (df_clean["HR"] >= 100),["Age","SEX_Female","SEX_Male","DBP","HR","SpO2","Nurse_KTAS","Expert_KTAS"]].reset_index()))

True

Both methods returned the same records and we know that becuase without reset_index they are equal and when the both use reset_index they are equal

In [177]:
df_clean.groupby('Group')['SpO2'].apply(lambda x: x.isnull().sum())

Group
1    688
2      9
Name: SpO2, dtype: int64

In [178]:
df_clean.groupby('Group')['SpO2'].apply(lambda x: x.isnull().mean()*100)

Group
1    100.000000
2      1.554404
Name: SpO2, dtype: float64

Group 1.
Very skewed towards group 1.
Maybe, since all local didnt have SpO2

In [179]:
analysis_df = df_clean.copy() 
analysis_df.drop(columns=['Sex','Patients number per hour','Diagnosis in ED','mistriage','Error_group','Low_SpO2','Senior'], inplace=True)
analysis_df.head(5)

,Group,SEX_Female,SEX_Male,Age,AGE_19,AGE_39,AGE_59,AGE_79,AGE_80+,Arrival mode,...,HR,RR,BT,SpO2,Nurse_KTAS,Disposition,Expert_KTAS,KTAS_match,Length of stay_min,KTAS duration_min
0,2,0,1,71,0,0,0,1,0,3,...,84.0,18.0,36.6,100.0,2,1,4,False,86,5.00
1,1,1,0,56,0,0,1,0,0,3,...,60.0,20.0,36.5,NaN,4,1,5,False,64,3.95
2,2,1,0,68,0,0,0,1,0,2,...,102.0,20.0,36.6,98.0,4,2,5,False,862,1.00
3,1,0,1,71,0,0,0,1,0,1,...,88.0,20.0,36.5,NaN,4,1,5,False,108,9.83
4,1,0,1,58,0,0,1,0,0,3,...,93.0,18.0,36.5,NaN,4,1,5,False,109,6.60

In [186]:
analysis_df.shape

(1267, 27)

In [187]:
analysis_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Group               1267 non-null   int64
 1   SEX_Female          1267 non-null   int64
 2   SEX_Male            1267 non-null   int64
 3   Age                 1267 non-null   int64
 4   AGE_19              1267 non-null   int64
 5   AGE_39              1267 non-null   int64
 6   AGE_59              1267 non-null   int64
 7   AGE_79              1267 non-null   int64
 8   AGE_80+             1267 non-null   int64
 9   Arrival mode        1267 non-null   int64
 10  Injury              1267 non-null   int64
 11  Chief_complaint     1246 non-null   str
 12  Mental              1267 non-null   int64
 13  Pain                1267 non-null   int64
 14  NRS_pain            711 non-null    float64
 15  SBP                 1242 non-null   float64
 16  DBP                 1238 non-null   float64
 17  HR                  1247 non-null   float64
 18  RR                  1245 non-null   float64
 19  BT                  1249 non-null   float64
 20  SpO2                570 non-null    float64
 21  Nurse_KTAS          1267 non-null   int64
 22  Disposition         1267 non-null   int64
 23  Expert_KTAS         1267 non-null   int64
 24  KTAS_match          1267 non-null   bool
 25  Length of stay_min  1267 non-null   int64
 26  KTAS duration_min   1267 non-null   float64
dtypes: bool(1), float64(8), int64(17), str(1)
memory usage: 258.7 KB

In [181]:
analysis_df.isnull().sum()

Group                   0
SEX_Female              0
SEX_Male                0
Age                     0
AGE_19                  0
AGE_39                  0
AGE_59                  0
AGE_79                  0
AGE_80+                 0
Arrival mode            0
Injury                  0
Chief_complaint        21
Mental                  0
Pain                    0
NRS_pain              556
SBP                    25
DBP                    29
HR                     20
RR                     22
BT                     18
SpO2                  697
Nurse_KTAS              0
Disposition             0
Expert_KTAS             0
KTAS_match              0
Length of stay_min      0
KTAS duration_min       0
dtype: int64

In [182]:
analysis_df.describe()

,Group,SEX_Female,SEX_Male,Age,AGE_19,AGE_39,AGE_59,AGE_79,AGE_80+,Arrival mode,...,DBP,HR,RR,BT,SpO2,Nurse_KTAS,Disposition,Expert_KTAS,Length of stay_min,KTAS duration_min
count,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,...,1238.000000,1247.000000,1245.000000,1249.000000,570.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000
mean,1.456985,0.478295,0.521705,54.423836,0.026835,0.243883,0.292818,0.344909,0.091555,2.820837,...,79.780291,83.963111,19.506827,36.580624,97.024561,3.335438,1.609313,3.265983,11016.102605,5.497466
std,0.498343,0.499726,0.499726,19.725033,0.161665,0.429593,0.455235,0.475526,0.288510,0.807904,...,15.154292,16.644096,2.016649,0.545708,4.350556,0.885391,1.157983,0.885803,80446.092065,3.459470
min,1.000000,0.000000,0.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,31.000000,32.000000,14.000000,35.000000,20.000000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,1.000000,0.000000,0.000000,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,70.000000,72.000000,18.000000,36.200000,97.000000,3.000000,1.000000,3.000000,133.000000,3.000000
50%,1.000000,0.000000,1.000000,57.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,...,80.000000,82.000000,20.000000,36.500000,98.000000,3.000000,1.000000,3.000000,274.000000,4.280000
75%,2.000000,1.000000,1.000000,71.000000,0.000000,0.000000,1.000000,1.000000,0.000000,3.000000,...,90.000000,96.000000,20.000000,36.800000,98.000000,4.000000,2.000000,4.000000,606.500000,7.000000
max,2.000000,1.000000,1.000000,96.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000,...,160.000000,148.000000,30.000000,41.000000,100.000000,5.000000,7.000000,5.000000,709510.000000,17.370000

In [183]:
analysis_df.to_csv('emergency_triage_clean.csv',index=False)

1. Which age group contains the most patients?
    The 60-79 age group had the most patients with 437 patients.
2. How many patients are aged 65 or older?
    There were 467 senior patients.
3. How many patients have SpO₂ below 95?
    There were 47 patients with a SpO2 below 95.
4. How many SpO₂ values are missing?
    There were 697 missing SpO2 values.
5. Why were missing SpO₂ values not classified as normal?
    They could be normal, but they could also be abnormal, so to make them all normal might skew the percentage of normal and abnormal SpO2 levels.
6. What percentage of nurse and expert KTAS values match?
    About 85%.
7. Were any duplicate rows found?
    There were no duplicate rows found.
8. Did Boolean indexing and `query()` produce the same result?
    They produced the same  result. 
9. Were missing SpO₂ values evenly distributed across `Group`?
    No, 100% of the SpO2 values in group 1 was missing while 1.6% of group 2 had missing SpO2 values.
10. What variables were included in `analysis_df`?
    Group,Age,Age_group,Sex_name,Arrival mode,Injury,Chief_complaint,Mental,Pain,NRS_pain,SBP,DBP,HR,RR,BT,SpO2,Nurse_KTAS,Expert_KTAS,KTAS_match,KTAS duration_min,Length of stay_min,Disposition
11. Which Pandas function was the most difficult to use?
    groupby, cause you also need to use apply and lambda and I didn't know that so that was a bit tricky.